name: Build APK

on:
  push:
    branches:
     - master  
  workflow_dispatch:   
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  

    - name: Decode Keystore file
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew    

    - name: Build APK
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_FILE_PATH: ${{ github.workspace }}/my-release-key.jks
        KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
