name: Build AAB And Publish To Bazaar

on:
  workflow_dispatch:  
    inputs:
      changelog_fa:
        description: 'توضیحات تغییرات نسخه (فارسی)'
        required: true
        default: 'بهبودهای کلی و رفع مشکلات'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download BundleSigner
        run: |
          curl -LO https://github.com/cafebazaar/bundle-signer/releases/download/v0.1.13/bundlesigner-0.1.13.jar

      - name: Decode Keystore File
        env:
          SIGNING_STORE: ${{ secrets.SIGNING_STORE_BASE64 }}
        run: echo "$SIGNING_STORE" | base64 --decode > release.jks

      - name: Grant Execute Permission to Gradle
        run: chmod +x gradlew

      - name: Build AAB
        run: ./gradlew bundleRelease
        env:
         KEYSTORE_FILE_PATH: ${{ github.workspace }}/release.jks
         KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
         KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      

      - name: Generate Bin File with BundleSigner
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          java -jar bundlesigner-0.1.13.jar genbin \
               --bundle app/build/outputs/bundle/release/app-release.aab \
               --bin . \
               --v2-signing-enabled true \
               --v3-signing-enabled false \
               --ks release.jks \
               --ks-pass pass:"$SIGNING_STORE_PASSWORD"

      - name: Upload Signed AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Upload Bin File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-bin
          path: app-release.bin

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Signed AAB
        uses: actions/download-artifact@v4
        with:
          name: signed-aab
          path: app/build/outputs/bundle/release/
          
      - name: Download Bin File
        uses: actions/download-artifact@v4
        with:
          name: signed-bin
          path: .
          
      - name: Create New Release in Cafe Bazaar
        run: |
          response=$(curl --silent --show-error --write-out "%{http_code}" --output response.json --request POST 'https://api.pishkhan.cafebazaar.ir/v1/apps/releases/' \
               --header 'CAFEBAZAAR-PISHKHAN-API-SECRET: ${{ secrets.BAZAR_API_KEY }}')

          if [[ "$response" -ne 201 ]]; then
              echo "❌ ایجاد انتشار جدید با مشکل مواجه شد. کد وضعیت: $response"
              cat response.json
              exit 1
          fi

      - name: Upload AAB To New Release
        run: |
          response=$(curl --silent --show-error --write-out "%{http_code}" --output response.json --verbose --request POST 'https://api.pishkhan.cafebazaar.ir/v1/apps/releases/upload-aab/' \
              --header 'CAFEBAZAAR-PISHKHAN-API-SECRET: ${{ secrets.BAZAR_API_KEY }}' \
              --header 'Content-Type: multipart/form-data' \
              --form 'aab=@app/build/outputs/bundle/release/app-release.aab')

          # بررسی کد وضعیت HTTP
          http_code=$(echo $response | tail -n 1)
          if [[ "$http_code" -ne 201 ]]; then
              echo "❌ آپلود AAB با مشکل مواجه شد. کد وضعیت: $http_code"
              cat response.json
              exit 1
          fi

          # بررسی موفقیت آپلود
          type=$(grep -o '"type": *"[^"]*' response.json | awk -F'"' '{print $4}')
          if [[ "$type" == "success" ]]; then
              echo "✅ آپلود موفقیت‌آمیز بود."
          else
              echo "❌ آپلود انجام نشد. پاسخ سرور:"
              cat response.json
              exit 1
          fi
      - name: Upload Bin To New Release
        run: |
          response=$(curl --silent --show-error --write-out "%{http_code}" --output response.json --verbose --request POST 'https://api.pishkhan.cafebazaar.ir/v1/apps/releases/upload-bin/' \
              --header 'CAFEBAZAAR-PISHKHAN-API-SECRET: ${{ secrets.BAZAR_API_KEY }}' \
              --header 'Content-Type: multipart/form-data' \
              --form 'file=@app-release.bin')

          # بررسی کد وضعیت HTTP
          http_code=$(echo $response | tail -n 1)
          if [[ "$http_code" -ne 201 ]]; then
              echo "❌ آپلود Bin با مشکل مواجه شد. کد وضعیت: $http_code"
              cat response.json
              exit 1
          fi

          # بررسی موفقیت آپلود
          type=$(grep -o '"type": *"[^"]*' response.json | awk -F'"' '{print $4}')
          if [[ "$type" == "success" ]]; then
              echo "✅ آپلود موفقیت‌آمیز بود."
          else
              echo "❌ آپلود انجام نشد. پاسخ سرور:"
              cat response.json
              exit 1
          fi
          
      - name: Check Bundle Status Periodically
        run: |
          while true; do
            response=$(curl --silent --request GET \
              --url "https://api.pishkhan.cafebazaar.ir/v1/apps/releases/bundle-status/" \
              --header "CAFEBAZAAR-PISHKHAN-API-SECRET: ${{ secrets.BAZAR_API_KEY }}")

            echo "Response: $response"

            # بررسی وضعیت پردازش باندل
            state=$(echo "$response" | grep -o '"state": *"[^"]*' | awk -F'"' '{print $4}')

            if [[ "$state" == "D" ]]; then
              echo "✅ Bundle processing completed."
              break
            fi

            echo "⏳ Bundle is still processing. Checking again in 60 seconds..."
            sleep 60
          done
          
      - name: Commit Release to Cafe Bazaar
        run: |
          response=$(curl --silent --show-error --write-out "%{http_code}" --output response.json --request POST 'https://api.pishkhan.cafebazaar.ir/v1/apps/releases/commit/' \
              --header 'CAFEBAZAAR-PISHKHAN-API-SECRET: ${{ secrets.BAZAR_API_KEY }}' \
              --header 'Content-Type: application/json' \
              --data '{
                "changelog_en": "",
                "changelog_fa": "${{ github.event.inputs.changelog_fa }}",
                "staged_rollout_percentage": 100,
                "developer_note": "",
                "auto_publish": true
              }')

          # بررسی کد وضعیت HTTP
          http_code=$(tail -n 1 <<< "$response")
          if [[ "$http_code" -ne 200 ]]; then
              echo "❌ کامیت انتشار با مشکل مواجه شد. کد وضعیت: $http_code"
              cat response.json
              exit 1
          fi

          # بررسی موفقیت درخواست
          type=$(grep -o '"type": *"[^"]*' response.json | awk -F'"' '{print $4}')
          if [[ "$type" == "success" ]]; then
              echo "✅ انتشار با موفقیت انجام شد."
          else
              echo "❌ انتشار انجام نشد. پاسخ سرور:"
              cat response.json
              exit 1
          fi
    
          
